POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Post title",
  "postType": "post",
  "slug": "post-slug",
  "status": "draft",
  "content": "Post content",
  "schema": "{\"key\":\"value\"}",
  "featuredImageUrl": "https://example.com/image.jpg",
  "publishOn": "2021-01-01T00:00:00.000Z",
  "tags": ["tag1", "tag2"],
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\": true, \"footerActive\": true}"
  }
}