POST http://localhost:3000/tags
Content-Type: application/json

{
  "name": "TAG 2",
  "slug": "tag-2-slug",
  "description": "dummy tag 2 description",
  "schema": "{\"key\":\"value\"}",
  "featuredImageUrl": "https://example.com/image.jpg"
}





POST http://localhost:3000/tags/create-many
Content-Type: application/json

{
  "tags": [
    {
      "name": "Javascript",
      "slug": "javascript",
      "description": "Javascript description",
      "schema": "{\"key\":\"value\"}",
      "featuredImageUrl": "https://example.com/image.jpg"
    },
        {
      "name": "Typescript",
      "slug": "typescript",
      "description": "Typescript description",
      "schema": "{\"key\":\"value\"}",
      "featuredImageUrl": "https://example.com/image.jpg"
    }
  ]
}